In [105]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
import scipy as sp
from scipy.optimize import minimize

In [11]:
sigma = 1
epsilon = np.random.normal(0, sigma, size=1)
print(epsilon)

[1.1770028]


In [14]:
import numpy as np

# 製品の数
M = 10  # 例として10を設定

# 正規分布 N(0, 1) に従う α_m^* を生成
alpha_star = np.random.normal(0, 1, size=M)

print(alpha_star)


[-2.9796084  -0.68517923  0.94454508  0.44924941 -0.26928939 -0.60884242
  1.41453088 -1.94114878 -0.11996866  0.78026589]


In [15]:
# 他の製品の数
M_prime = 10  # 例として10を設定

# 基底関数の数
D = 3  # 例として3を設定

# 正規分布 N(0, 1) に従う β_mm'd^* を生成
beta_star = np.random.normal(0, 1, size=(M, M_prime, D))

print(beta_star)


[[[ 1.11593946e+00  9.11625414e-01  6.23589291e-01]
  [-1.63320513e+00  3.02418597e-01  6.50544138e-01]
  [ 8.90583220e-02  4.62172183e-01 -1.43990842e+00]
  [-9.94194093e-01  1.21721821e-01  4.98154349e-01]
  [-3.61366076e-02  4.04186908e-01 -1.58127200e-01]
  [-1.11854610e+00 -6.62011714e-01 -3.69542017e-02]
  [-7.84610140e-01  1.75844183e+00 -3.86462871e-02]
  [-2.43896849e-01 -1.26652532e+00 -7.40791461e-01]
  [-2.26068297e+00  7.29502066e-01 -7.46571467e-02]
  [-2.73476843e+00  1.61835878e+00  3.39023310e-01]]

 [[ 1.89842660e-01  6.19177879e-01  5.14324317e-01]
  [-1.91899120e+00 -2.05760390e+00 -9.15662705e-01]
  [-9.82099721e-01  2.38569353e-01 -2.37196227e-01]
  [-2.42174277e-01  3.68683390e-02  6.03017062e-02]
  [ 5.35449434e-01  9.81389561e-01  9.94085021e-01]
  [-1.51662039e+00 -4.96100489e-02  5.67734349e-01]
  [ 9.74900588e-02 -8.07130436e-01 -2.14251321e+00]
  [-1.06135754e+00  6.09831510e-01 -1.07720880e-01]
  [ 1.02733172e+00  3.60361782e-01 -7.46931930e-01]
  [-2.9583

In [16]:
beta_star = np.random.normal(0, 1, size=(2, 3, 4))

print(beta_star)

[[[-2.20585849  0.25691054 -1.34982436  1.63670396]
  [-0.66607421  0.31361341 -0.30175078  0.2263655 ]
  [-0.32023195  0.01697295  0.75490952  0.03284359]]

 [[ 0.09324875 -0.23579906  1.39488651 -1.09818347]
  [-0.04717417 -0.67162937 -0.96567888  0.18778974]
  [ 0.62879404 -0.81017638  0.2388047  -1.87611371]]]


In [18]:
for i in beta_star :
    for j in i:
        print(j)

[-2.20585849  0.25691054 -1.34982436  1.63670396]
[-0.66607421  0.31361341 -0.30175078  0.2263655 ]
[-0.32023195  0.01697295  0.75490952  0.03284359]
[ 0.09324875 -0.23579906  1.39488651 -1.09818347]
[-0.04717417 -0.67162937 -0.96567888  0.18778974]
[ 0.62879404 -0.81017638  0.2388047  -1.87611371]


In [43]:
# 価格を生成する関数
def create_price(M, d) :
    price = np.random.randint(d, 3*d, size=M)
    return price   

In [44]:
# alphaを作成する関数
def alpha_star(M) :
    alpha_star = np.random.normal(0, 1, size=M)
    return alpha_star

In [45]:
# betaを作成する関数
def beta_star(M, M_prime) :
    beta_star = np.random.normal(0, 1, size=(M, M_prime, 3))
    return beta_star

In [46]:
beta_star(2, 2)

array([[[ 1.24506421, -0.5264943 ,  0.68070877],
        [ 1.09991819, -0.17332801, -1.22542877]],

       [[ 0.63159642,  1.07191256, -0.31627389],
        [-0.66282552,  1.06411311,  1.27134775]]])

In [47]:
# phi関数
def phi(price ,beta) :
    phi = beta[0]*price + beta[1]*price**2 + beta[2]*(1/price)
    return phi

In [56]:
price_1=create_price(10, 100)
alpha_1=alpha_star(10)
beta_1=beta_star(10, 10)

In [57]:
phi(price_1[0], beta_1[0][0])

66720.73811913021

In [50]:
beta_1[0][0][2]*(1/price_1[0])

0.008590766424853513

In [61]:
quantity = []
for m in range(10) :
    sum_beta = 0
    for m_prime in range(10) :
        sum_beta += phi(price_1[m], beta_1[m][m_prime])
    quantity.append(alpha_1[m] + sum_beta + np.random.normal(0, sigma, size=1))

In [62]:
quantity

[array([26873.01145341]),
 array([36748.76123274]),
 array([292681.56622489]),
 array([120819.57312637]),
 array([23971.56681131]),
 array([-132785.96423462]),
 array([-230921.88398741]),
 array([-42569.77181036]),
 array([-3655.14087756]),
 array([268886.80569682])]

In [63]:
sum(quantity)

array([360048.52363559])

In [74]:
M = 50
# このデータにおけるalpha,betaを作成
alpha=alpha_star(M)
beta=beta_star(M, M)

In [75]:

# 価格を入れるリストを作成
price_list = []
# 量を入れるリストを作成
quantity_list = []
for i in range(10000) :
    price = create_price(M, 100)
    price_list.append(price)
    quantity = []
    for m in range(M) :
        sum_beta = 0
        for m_prime in range(M) :
            sum_beta += phi(price[m], beta[m][m_prime])
        quantity.append(alpha[m] + sum_beta + np.random.normal(0, sigma, size=1))
    quantity_list.append(sum(quantity))



In [76]:
# 列名の作成
column_names = [f'prodact_{i+1}' for i in range(50)]

In [77]:
# データフレームの作成
df_price = pd.DataFrame(price_list, columns=column_names)

In [78]:
df_price.head()

prodact_1  prodact_2  prodact_3  prodact_4  prodact_5  prodact_6  \
0        282        163        209        138        287        125   
1        186        219        110        195        183        260   
2        269        296        127        144        172        257   
3        210        236        171        290        257        287   
4        196        225        271        206        188        257   

   prodact_7  prodact_8  prodact_9  prodact_10  ...  prodact_41  prodact_42  \
0        226        170        180         282  ...         148         203   
1        167        140        195         105  ...         118         200   
2        129        101        154         263  ...         289         259   
3        208        218        153         251  ...         127         273   
4        124        181        166         157  ...         255         190   

   prodact_43  prodact_44  prodact_45  prodact_46  prodact_47  prodact_48  \
0         200         226         275         214         177         147   
1         270         163         254         273         176         248   
2         205         178         114         197         138         288   
3         299         137         246         273         270         157   
4         128         118         274         277         113         148   

   prodact_49  prodact_50  
0         195         152  
1         282         231  
2         233         123  
3         137         207  
4         285         131  

[5 rows x 50 columns]

In [79]:
# 売上の追加
df_price['sales'] = quantity_list

In [80]:
df_price

prodact_1  prodact_2  prodact_3  prodact_4  prodact_5  prodact_6  \
0           282        163        209        138        287        125   
1           186        219        110        195        183        260   
2           269        296        127        144        172        257   
3           210        236        171        290        257        287   
4           196        225        271        206        188        257   
...         ...        ...        ...        ...        ...        ...   
9995        138        289        157        134        139        161   
9996        248        295        168        225        254        227   
9997        292        255        127        173        169        248   
9998        166        134        217        229        251        238   
9999        271        101        283        135        155        212   

      prodact_7  prodact_8  prodact_9  prodact_10  ...  prodact_42  \
0           226        170        180         282  ...         203   
1           167        140        195         105  ...         200   
2           129        101        154         263  ...         259   
3           208        218        153         251  ...         273   
4           124        181        166         157  ...         190   
...         ...        ...        ...         ...  ...         ...   
9995        177        173        193         210  ...         176   
9996        299        236        206         134  ...         203   
9997        277        178        236         165  ...         144   
9998        204        195        173         110  ...         283   
9999        150        185        134         175  ...         236   

      prodact_43  prodact_44  prodact_45  prodact_46  prodact_47  prodact_48  \
0            200         226         275         214         177         147   
1            270         163         254         273         176         248   
2            205         178         114         197         138         288   
3            299         137         246         273         270         157   
4            128         118         274         277         113         148   
...          ...         ...         ...         ...         ...         ...   
9995         200         109         293         102         255         174   
9996         292         260         160         104         245         217   
9997         103         263         192         276         176         124   
9998         124         211         148         161         161         199   
9999         270         153         260         226         160         292   

      prodact_49  prodact_50                  sales  
0            195         152  [-209595.72796593746]  
1            282         231    [1552241.646175111]  
2            233         123  [-247707.04741686635]  
3            137         207   [1229705.3501252055]  
4            285         131    [648091.6441728275]  
...          ...         ...                    ...  
9995         167         152  [-1162378.3357511319]  
9996         106         226  [-1747268.4600141854]  
9997         277         167    [811002.1888336862]  
9998         120         253   [1218855.5128839146]  
9999         288         271   [2058335.7795295871]  

[10000 rows x 51 columns]

In [81]:
df_price.dtypes

prodact_1      int32
prodact_2      int32
prodact_3      int32
prodact_4      int32
prodact_5      int32
prodact_6      int32
prodact_7      int32
prodact_8      int32
prodact_9      int32
prodact_10     int32
prodact_11     int32
prodact_12     int32
prodact_13     int32
prodact_14     int32
prodact_15     int32
prodact_16     int32
prodact_17     int32
prodact_18     int32
prodact_19     int32
prodact_20     int32
prodact_21     int32
prodact_22     int32
prodact_23     int32
prodact_24     int32
prodact_25     int32
prodact_26     int32
prodact_27     int32
prodact_28     int32
prodact_29     int32
prodact_30     int32
prodact_31     int32
prodact_32     int32
prodact_33     int32
prodact_34     int32
prodact_35     int32
prodact_36     int32
prodact_37     int32
prodact_38     int32
prodact_39     int32
prodact_40     int32
prodact_41     int32
prodact_42     int32
prodact_43     int32
prodact_44     int32
prodact_45     int32
prodact_46     int32
prodact_47     int32
prodact_48   

In [82]:
# 売上をfloat型に変換
df_price['sales'] = df_price['sales'].astype(float)

In [83]:
# 確認
df_price.dtypes

prodact_1       int32
prodact_2       int32
prodact_3       int32
prodact_4       int32
prodact_5       int32
prodact_6       int32
prodact_7       int32
prodact_8       int32
prodact_9       int32
prodact_10      int32
prodact_11      int32
prodact_12      int32
prodact_13      int32
prodact_14      int32
prodact_15      int32
prodact_16      int32
prodact_17      int32
prodact_18      int32
prodact_19      int32
prodact_20      int32
prodact_21      int32
prodact_22      int32
prodact_23      int32
prodact_24      int32
prodact_25      int32
prodact_26      int32
prodact_27      int32
prodact_28      int32
prodact_29      int32
prodact_30      int32
prodact_31      int32
prodact_32      int32
prodact_33      int32
prodact_34      int32
prodact_35      int32
prodact_36      int32
prodact_37      int32
prodact_38      int32
prodact_39      int32
prodact_40      int32
prodact_41      int32
prodact_42      int32
prodact_43      int32
prodact_44      int32
prodact_45      int32
prodact_46

In [86]:
# データの確認
df_price.head()

prodact_1  prodact_2  prodact_3  prodact_4  prodact_5  prodact_6  \
0        282        163        209        138        287        125   
1        186        219        110        195        183        260   
2        269        296        127        144        172        257   
3        210        236        171        290        257        287   
4        196        225        271        206        188        257   

   prodact_7  prodact_8  prodact_9  prodact_10  ...  prodact_42  prodact_43  \
0        226        170        180         282  ...         203         200   
1        167        140        195         105  ...         200         270   
2        129        101        154         263  ...         259         205   
3        208        218        153         251  ...         273         299   
4        124        181        166         157  ...         190         128   

   prodact_44  prodact_45  prodact_46  prodact_47  prodact_48  prodact_49  \
0         226         275         214         177         147         195   
1         163         254         273         176         248         282   
2         178         114         197         138         288         233   
3         137         246         273         270         157         137   
4         118         274         277         113         148         285   

   prodact_50         sales  
0         152 -2.095957e+05  
1         231  1.552242e+06  
2         123 -2.477070e+05  
3         207  1.229705e+06  
4         131  6.480916e+05  

[5 rows x 51 columns]

In [91]:
X = df_price[column_names]

In [93]:
Y = df_price['sales']

In [94]:
# XとYを学習用とテスト用に分割
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=0)

In [95]:
# モデルの作成
lr = LinearRegression()

In [96]:
# テストデータを用いてモデルを学習
lr.fit(X_train, Y_train)

LinearRegression()

In [97]:
# テストデータを用いて予測
Y_pred = lr.predict(X_test)

In [102]:
# 予測結果の精度を確認
print(mean_squared_error(Y_test, Y_pred))

22085610040.16309


In [103]:
# モデルの係数を確認
lr.coef_

array([ 2259.32830975, -1344.52556362,  1097.62315259, -3913.31777988,
        2162.36058765, -1415.26482004,  -463.63837204, -2818.41985316,
       -1242.36918481, -1319.65245333,  1318.65690037, -3171.50554176,
        3176.08138339, -2373.55966439,  1173.49263565, -1435.48982321,
        3686.6943691 , -1749.97993862,  1996.47300298,  2356.61869866,
       -2778.36246751, -7069.54844138, -3715.82758597, -2407.56884078,
        2395.06650076,  -946.63290202,  1064.83221196,   283.96469664,
        4348.0286548 ,  -568.29887706,  4125.50381251,  1677.43167624,
         175.29803986, -2269.78562217,  1645.8799917 ,  3982.69394842,
       -1472.92807382,   -55.11360304, -7041.35104742,  -771.84054531,
       -1211.90419051,  3931.44381567,  -304.71893973, -2671.06796434,
       -3004.12326397,  4643.82746656,  1742.76934321,  -565.02896361,
        4685.50935583,  2082.36818575])

In [104]:
# 目的関数の定義
def objective_function(params, X, y):
    # paramsは [係数1, 係数2, ..., バイアス] という形
    coef = params[:-1]
    intercept = params[-1]
    
    # 線形回帰モデルの予測値
    y_pred = np.dot(X, coef) + intercept
    
    # 二乗誤差の和を計算
    error = np.sum((y_pred - y) ** 2)
    
    return error


In [111]:
# 目的関数の定義（売上の負の値を返す）
def objective_function(prices, coef, intercept):
    # 価格に基づく売上の予測
    sales = np.dot(prices, coef) + intercept
    
    # 売上を最大化するために、負の値を返す（minimizeは最小化を行うため）
    return -sales

In [112]:
# 初期価格（例えば、各製品の初期価格を100とする）
initial_prices = np.full(M, 100)


In [114]:
print(initial_prices)

[100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100
 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100
 100 100 100 100 100 100 100 100 100 100 100 100 100 100]


In [113]:
# 線形回帰モデルの係数とバイアスを取得
coef = lr.coef_
intercept = lr.intercept_

# Nelder-Mead法を用いて最適化
result = minimize(objective_function, initial_prices, args=(coef, intercept), method='Nelder-Mead')

# 最適化された価格
optimal_prices = result.x

print("Optimal Prices:", optimal_prices)

Optimal Prices: [ 4.43199746e+14 -1.83198647e+14  8.75758770e+13 -6.76302315e+14
 -8.52868923e+14 -2.84017817e+14 -1.01752103e+14 -2.70128021e+14
  4.64547109e+13 -1.59881197e+15  3.34442550e+14 -3.15360532e+14
  1.82317803e+15 -1.29853632e+14  3.56459646e+14  1.42841386e+12
  6.81842758e+14 -8.17954704e+13  8.11031206e+14  4.67727237e+14
 -2.69199043e+14 -3.49547906e+15 -2.62444736e+14 -1.43677204e+15
 -1.00909897e+15  1.66634048e+15 -1.94641429e+13 -8.83616382e+14
  1.12001200e+15  1.55218969e+14  6.76145898e+14 -3.94092506e+14
 -2.15126397e+14  1.43112117e+15  1.36038139e+15  6.95154902e+14
 -4.87588980e+14 -3.36659811e+14 -7.33798028e+14  3.25421440e+13
 -3.59962121e+14  5.55915999e+14  7.84905999e+14  5.64529653e+13
  3.13052223e+13  2.29658216e+14  2.84704299e+14 -1.45148754e+14
  6.56006657e+14  3.01840805e+13]


In [115]:
optimal_sales = np.dot(optimal_prices, coef) + intercept
print("Optimal Sales:", optimal_sales)

Optimal Sales: 6.580031149350135e+19


In [116]:
def sales_function(price, alpha, beta, phi, sigma):
    M = len(price)
    total_sales = 0
    
    for m in range(M):
        sum_beta = 0
        for m_prime in range(M):
            sum_beta += phi(price[m], beta[m][m_prime])
        
        quantity = alpha[m] + sum_beta + np.random.normal(0, sigma)
        total_sales += quantity
    
    return total_sales


In [117]:
def objective_function(price, alpha, beta, sigma):
    # 売上の負の値を返す（売上を最大化するため）
    return -sales_function(price, alpha, beta, phi, sigma)


In [118]:
# 最適化の実行
result = minimize(objective_function, initial_prices, args=(alpha, beta, sigma), method='Nelder-Mead')

# 最適化された価格
optimal_prices = result.x

print("Optimal Prices:", optimal_prices)

# 最適化された価格での売上
optimal_sales = -result.fun
print("Optimal Sales:", optimal_sales)

Optimal Prices: [-3.24381470e+15  3.12825068e+13  3.02606095e+14 -5.65032435e+14
  1.08179871e+14 -1.08531552e+15 -3.96761104e+12 -3.80939428e+14
 -5.26916938e+14  1.09497922e+15 -1.10827405e+14 -2.42054473e+14
  8.39394862e+14 -2.95098031e+14  3.59980698e+14 -2.90156118e+12
  1.57673773e+15 -2.21858811e+14  5.46641604e+14  7.51048198e+14
 -4.31902173e+14 -1.59308063e+15 -1.15269322e+15  7.29703784e+14
  6.45306441e+14 -4.73505009e+13 -3.21843690e+14  1.85470193e+14
  8.98265386e+14 -2.07086545e+13  7.44783485e+14 -9.79360159e+14
  9.85386677e+14 -4.30920991e+14 -9.75377779e+13  8.16356378e+14
  1.92204803e+13  1.14614229e+14 -4.72508732e+14 -1.41157969e+14
 -1.39633346e+14 -4.63778744e+14  5.27965305e+14  6.85538132e+13
 -3.60775531e+14  5.13986096e+14  3.52599488e+14 -1.33495595e+13
  6.83547935e+14  4.01855112e+14]
Optimal Sales: 5.12692970784268e+31
